development:
  adapter: mysql2
  encoding: utf8
  database: ahad
  username: root
  password: 12345678
  host: 127.0.0.1
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: ahad
  username: root
  password: 12345678
  host: 127.0.0.1
  port: 3306

# setup for heroku
production:
  adapter: mysql2
  encoding: utf8
  database: ahad
  username: root
  password: 12345678
  host: 127.0.0.1
  port: 3306