development:
  adapter: postgresql
  encoding: unicode
  database: ahad
  pool: 5
  username: root
  password: root

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: root
  password: root

production:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: root
  password: root